(() => {
  const PHONE_DISPLAY = "607-207-6969";
  const PHONE_LINK = "tel:16072076969";
  const EMAIL = "joshuawhite@howardhanna.com";

  const LINKS = {
    search: "search.html",
    value: "https://homevalue.howardhanna.com/joshuawilliamwhite",
    mortgage: "https://mymortgageapp.1stprioritymortgage.com/dr/c/1hy1e",
    hometrackr: "hometrackr.html",
    appStore: "https://apps.apple.com/us/app/hometrackr-home-log/id6785076449",
    findFirst: "https://joshuawilliamwhite.howardhanna.com/find-it-first",
    hannaList: "https://joshuawilliamwhite.howardhanna.com/hanna-list",
    neighborhood: "https://joshuawilliamwhite.howardhanna.com/neighborhoodnews",
    google: "https://share.google/YbejLCxPQaZYuZrGc",
    zillow: "https://www.zillow.com/profile/JoshuaWhiteRealtor",
    facebook: "https://www.facebook.com/JoshuaWhiteRealtor",
    instagram: "https://www.instagram.com/joshuawwhiterealtor/",
    youtube: "https://www.youtube.com/@joshuawhiterealtor"
  };

  const leadFormUrl = (subject, body) => `mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

  function normalizeKikiBranding() {
    document.querySelectorAll('.nav-cta').forEach(link => {
      link.textContent = 'Meet Kiki';
      if (!link.getAttribute('href') || link.getAttribute('href') === '#ai') link.setAttribute('href', 'index.html#ai');
    });
    document.querySelectorAll('a,button').forEach(el => {
      const text = (el.textContent || '').trim();
      if (text === 'Joshua AI' || text === 'Ask Joshua AI') el.textContent = text.startsWith('Ask') ? 'Ask Kiki' : 'Meet Kiki';
    });
  }

  const intents = [
    {keys:["home value","worth","valuation","cma","sell","selling","seller","list my house","list my home","market analysis"],answer:`Absolutely — I can help you start a seller plan.\n\nFor a quick estimate, use Joshua's Howard Hanna home value tool. For a detailed pricing strategy, Joshua should review condition, updates, location, and recent comparable sales.`,actions:[["Get Home Value",LINKS.value],["Request Seller Review",leadFormUrl("Seller / Home Value Request","Hi Joshua, I would like a home value review.\n\nProperty address:\nTimeline:\nMajor updates:\nBest phone/email:")],["Call/Text Joshua",PHONE_LINK]]},
    {keys:["buy","buyer","buying","first time","showing","tour","schedule showing","see a house","look at homes"],answer:`Great — buying starts with budget, location, and must-haves. A pre-approval is strongly recommended before serious showings or making an offer.`,actions:[["Search Homes",LINKS.search],["Mortgage Help",LINKS.mortgage],["Send Buyer Details",leadFormUrl("Buyer Help Request","Hi Joshua, I am interested in buying.\n\nDesired area:\nPrice range:\nMust-haves:\nTimeline:\nPre-approved?\nBest phone/email:")]]},
    {keys:["mortgage","loan","lender","financing","rate","payment","1st priority","preapproval","pre-approval","afford"],answer:`Joshua can connect you with 1st Priority Mortgage to review loan options, affordability, payment estimates, and pre-approval steps.`,actions:[["Start Mortgage Application",LINKS.mortgage],["Ask Joshua",leadFormUrl("Mortgage Question","Hi Joshua, I have a mortgage/pre-approval question.\n\nQuestion:\nBest phone/email:")]]},
    {keys:["hometrackr","home tracker","home log","maintenance app","paint colors","warranties","receipts"],answer:`HomeTrackr is Joshua's home log app. It helps homeowners, buyers, sellers, renters, and landlords organize maintenance, projects, paint colors, appliances, warranties, receipts, photos, vehicles, and more.`,actions:[["Learn About HomeTrackr",LINKS.hometrackr],["Download on App Store",LINKS.appStore]]},
    {keys:["listing","listings","homes","house","property","properties","acreage","land","farm","rent","rental","mls","search"],answer:`You can search homes directly on this website using Joshua's RealScout search. If you find a property you like, Joshua can help confirm availability and arrange a showing.`,actions:[["Search Homes",LINKS.search],["View Listings","listings.html"],["Find It First",LINKS.findFirst]]},
    {keys:["review","reviews","testimonial","testimonials","zillow","google","rating"],answer:`You can read Joshua's reviews on Google, Zillow, and the testimonials page.`,actions:[["Google Reviews",LINKS.google],["Zillow Profile",LINKS.zillow],["Testimonials","reviews.html"]]},
    {keys:["contact","call","text","phone","email","reach","appointment","schedule","meet","consultation"],answer:`You can reach Joshua directly by call/text at ${PHONE_DISPLAY} or email at ${EMAIL}.`,actions:[["Call/Text Joshua",PHONE_LINK],["Email Joshua",leadFormUrl("Website Inquiry","Hi Joshua, I visited your website and would like help with:\n\nName:\nPhone:\nEmail:\nQuestion:")],["Contact Page","contact.html"]]},
    {keys:["area","service area","corning","painted post","elmira","horseheads","big flats","sayre","athens","wellsboro","mansfield","troy","canton"],answer:`Joshua is licensed in New York and Pennsylvania and serves the Southern Tier of NY and Northern Tier of PA.`,actions:[["Search Homes",LINKS.search],["Neighborhood News",LINKS.neighborhood],["Contact Joshua","contact.html"]]}
  ];

  function createStyles(){const s=document.createElement('style');s.textContent=`.jw-ai-launcher{position:fixed;right:22px;bottom:22px;z-index:9999;border:0;border-radius:999px;background:#b88128;color:#fff;padding:15px 20px;font-weight:900;box-shadow:0 18px 44px rgba(14,58,50,.28);cursor:pointer;font-size:16px;display:flex;gap:9px;align-items:center}.jw-ai-window{position:fixed;right:22px;bottom:86px;z-index:9999;width:min(460px,calc(100vw - 28px));height:min(700px,calc(100vh - 118px));background:#fff;border:1px solid rgba(184,161,113,.45);border-radius:24px;box-shadow:0 24px 80px rgba(14,58,50,.28);overflow:hidden;display:none;flex-direction:column;font-family:Arial,Helvetica,sans-serif}.jw-ai-window.open{display:flex}.jw-ai-header{background:linear-gradient(135deg,#0e3a32,#005a4e);color:#fff;padding:18px;display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.jw-ai-header strong{display:block;font-size:21px}.jw-ai-header span{display:block;color:#dbcfa7;font-size:13px;margin-top:3px}.jw-ai-close{background:transparent;color:#fff;border:1px solid rgba(255,255,255,.45);border-radius:999px;width:34px;height:34px;cursor:pointer;font-size:20px}.jw-ai-intro{background:#ece9d3;border-bottom:1px solid rgba(184,161,113,.30);padding:12px 16px;color:#0e3a32;font-weight:800;font-size:13px}.jw-ai-messages{padding:16px;overflow:auto;display:flex;flex-direction:column;gap:12px;flex:1;background:linear-gradient(180deg,#fff,#ece9d3)}.jw-msg{max-width:90%;padding:12px 14px;border-radius:18px;font-size:14px;line-height:1.45;white-space:pre-wrap}.jw-bot{background:#fff;border:1px solid rgba(184,161,113,.36);color:#2e2e2e;align-self:flex-start}.jw-user{background:#0e3a32;color:#fff;align-self:flex-end}.jw-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.jw-actions a,.jw-chip{border:1px solid rgba(14,58,50,.18);background:#d0e2da;color:#0e3a32;border-radius:999px;padding:8px 10px;font-weight:800;font-size:12px;text-decoration:none;cursor:pointer}.jw-quick{padding:12px 14px;border-top:1px solid rgba(184,161,113,.30);display:flex;gap:8px;flex-wrap:wrap;background:#fff}.jw-ai-form{display:flex;gap:8px;padding:12px;background:#fff;border-top:1px solid rgba(184,161,113,.30)}.jw-ai-input{flex:1;border:1px solid rgba(14,58,50,.22);border-radius:999px;padding:12px 14px;font-size:14px}.jw-ai-send{border:0;border-radius:999px;background:#b88128;color:#fff;font-weight:900;padding:0 16px;cursor:pointer}@media(max-width:620px){.jw-ai-window{right:14px;bottom:78px;height:76vh}.jw-ai-launcher{right:14px;bottom:14px}.jw-ai-launcher span:last-child{display:none}}`;document.head.appendChild(s)}
  function botResponse(text){const q=text.toLowerCase();const m=intents.map(intent=>({intent,score:intent.keys.reduce((n,key)=>n+(q.includes(key)?key.length:0),0)})).sort((a,b)=>b.score-a.score)[0];return m&&m.score>0?m.intent:{answer:`I can help with buying, selling, home values, home search, mortgage options, HomeTrackr, reviews, local areas, or connecting you with Joshua.`,actions:[["Search Homes",LINKS.search],["Home Value",LINKS.value],["Contact Joshua","contact.html"]]}}
  function addMessage(container,type,text,actions=[]){const msg=document.createElement('div');msg.className=`jw-msg ${type==='user'?'jw-user':'jw-bot'}`;msg.textContent=text;if(actions.length){const wrap=document.createElement('div');wrap.className='jw-actions';actions.forEach(([label,href])=>{const a=document.createElement('a');a.textContent=label;a.href=href;if(href.startsWith('http')){a.target='_blank';a.rel='noopener'}wrap.appendChild(a)});msg.appendChild(wrap)}container.appendChild(msg);container.scrollTop=container.scrollHeight}
  function buildWidget(){normalizeKikiBranding();createStyles();const launcher=document.createElement('button');launcher.className='jw-ai-launcher';launcher.innerHTML='<span>💬</span><span>Ask Kiki</span>';const windowEl=document.createElement('section');windowEl.className='jw-ai-window';windowEl.innerHTML='<div class="jw-ai-header"><div><strong>Kiki</strong><span>Joshua White\'s AI Real Estate Assistant</span></div><button class="jw-ai-close" aria-label="Close Kiki">×</button></div><div class="jw-ai-intro">✨ Try: “What is my home worth?” or “I want to buy in Corning.”</div><div class="jw-ai-messages"></div><div class="jw-quick"><button class="jw-chip" data-question="I want to search homes">Search homes</button><button class="jw-chip" data-question="What is my home worth?">Home value</button><button class="jw-chip" data-question="I want to buy a home">Buying</button><button class="jw-chip" data-question="I want to sell my house">Selling</button><button class="jw-chip" data-question="What is HomeTrackr?">HomeTrackr</button></div><form class="jw-ai-form"><input class="jw-ai-input" type="text" placeholder="Ask Kiki a real estate question..." /><button class="jw-ai-send" type="submit">Send</button></form>';document.body.append(windowEl,launcher);const messages=windowEl.querySelector('.jw-ai-messages');const input=windowEl.querySelector('.jw-ai-input');addMessage(messages,'bot',`Hi, I'm Kiki — Joshua White's digital real estate assistant. I can help with home search, home values, buying, selling, mortgage options, reviews, HomeTrackr, or connecting you with Joshua. What can I help with today?`,[["Search Homes",LINKS.search],["Home Value",LINKS.value],["Contact Joshua","contact.html"]]);launcher.addEventListener('click',()=>{windowEl.classList.toggle('open');if(windowEl.classList.contains('open'))input.focus()});windowEl.querySelector('.jw-ai-close').addEventListener('click',()=>windowEl.classList.remove('open'));windowEl.querySelectorAll('.jw-chip').forEach(chip=>chip.addEventListener('click',()=>{const q=chip.dataset.question;addMessage(messages,'user',q);const reply=botResponse(q);setTimeout(()=>addMessage(messages,'bot',reply.answer,reply.actions),200)}));windowEl.querySelector('.jw-ai-form').addEventListener('submit',e=>{e.preventDefault();const q=input.value.trim();if(!q)return;input.value='';addMessage(messages,'user',q);const reply=botResponse(q);setTimeout(()=>addMessage(messages,'bot',reply.answer,reply.actions),250)});setTimeout(normalizeKikiBranding,500)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',buildWidget);else buildWidget();
})();